"""add fields

Revision ID: 0e51254f30e8
Revises: db603444ff08
Create Date: 2024-01-08 21:40:26.291318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e51254f30e8"
down_revision: Union[str, None] = "db603444ff08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_status",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=32), nullable=True),
        sa.Column("ext_id", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ext_id"),
    )
    op.add_column("users", sa.Column("phone", sa.String(length=16), nullable=True))
    op.add_column("users", sa.Column("latitude", sa.DECIMAL(), nullable=True))
    op.add_column("users", sa.Column("longitude", sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "longitude")
    op.drop_column("users", "latitude")
    op.drop_column("users", "phone")
    op.drop_table("user_status")
    # ### end Alembic commands ###
