"""init_

Revision ID: db603444ff08
Revises: d1882a969242
Create Date: 2024-01-08 18:29:00.374797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db603444ff08"
down_revision: Union[str, None] = "d1882a969242"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "characters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("character_id", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_path", sa.String(length=64), nullable=True),
        sa.Column("cost_coins", sa.Integer(), nullable=True),
        sa.Column("cost_crystals", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("character_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_id", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_path", sa.String(length=64), nullable=True),
        sa.Column("cost_coins", sa.Integer(), nullable=True),
        sa.Column("cost_crystals", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("users", sa.Column("image_path", sa.String(length=64), nullable=True))
    op.add_column("users", sa.Column("balance_coins", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("balance_crystals", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "balance_crystals")
    op.drop_column("users", "balance_coins")
    op.drop_column("users", "image_path")
    op.drop_table("items")
    op.drop_table("characters")
    # ### end Alembic commands ###
